logging:
  level: "debug"
  encoding: "json"
  outputPaths: [ "stdout" ]
  encoderConfig:
    messageKey: "msg"
    levelKey: "level"
    timeKey: "timestemp"
server:
  port: 3012
db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  timeout: 10000000000 #10 seconds
  name: "users"
  schema: "public"
  migration:
    run: false #need to be set on true only with new migration file
    steps: 0 #number of files to call - negative if we go back
    files: "../user-store/datasource/postgresql/migrations"